# Generated by Django 6.0.5 on 2026-05-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionpackage',
            name='storage_bytes',
        ),
        migrations.AddField(
            model_name='subscriptionpackage',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionpackage',
            name='storage_gb',
            field=models.BigIntegerField(default=1),
        ),
    ]
